Write-Host "Testing Updated Balance System" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host "MCP server now returns actual balances - no conversion needed" -ForegroundColor Yellow
Write-Host ""

try {
    $body = @{
        message = "get balance of 0x6492772d1474ffa1ed6944e86735848c253bb007 on arbitrum"
    } | ConvertTo-Json
    
    Write-Host "Sending request..." -ForegroundColor Gray
    $response = Invoke-RestMethod -Uri "http://localhost:3000/api/chat" -Method POST -ContentType "application/json" -Body $body -TimeoutSec 20
    
    Write-Host "✅ Response received!" -ForegroundColor Green
    Write-Host ""
    Write-Host "RESPONSE:" -ForegroundColor Cyan
    Write-Host "=========" -ForegroundColor Cyan
    Write-Host $response.response -ForegroundColor White
    Write-Host ""
    
    if ($response.toolsUsed -and $response.toolsUsed.Count -gt 0) {
        Write-Host "✅ Tool Used: $($response.toolsUsed[0].name)" -ForegroundColor Green
        Write-Host "Tool Result Sample:" -ForegroundColor Gray
        Write-Host $response.toolsUsed[0].result.substring(0, [Math]::Min(100, $response.toolsUsed[0].result.Length)) -ForegroundColor Gray
    } else {
        Write-Host "❌ No tool was used" -ForegroundColor Red
    }
    
    # Check for clean response (no disclaimers)
    $unwantedPatterns = @("Note:", "AI", "simulated", "generated by", "real-time")
    $foundUnwanted = @()
    foreach ($pattern in $unwantedPatterns) {
        if ($response.response -match $pattern) {
            $foundUnwanted += $pattern
        }
    }
    
    if ($foundUnwanted.Count -eq 0) {
        Write-Host "✅ Clean response - no disclaimers" -ForegroundColor Green
    } else {
        Write-Host "⚠️ Found unwanted patterns: $($foundUnwanted -join ', ')" -ForegroundColor Yellow
    }
    
} catch {
    Write-Host "❌ Error: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""
Write-Host "Test completed. The system should now use balances directly from MCP server." -ForegroundColor Gray
